# Generated by Django 5.1.4 on 2024-12-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0004_rename_image_url_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Колір")),
                (
                    "processor",
                    models.CharField(max_length=100, verbose_name="Процесор"),
                ),
                (
                    "ram",
                    models.PositiveIntegerField(
                        verbose_name="Оперативна пам'ять (RAM) в ГБ"
                    ),
                ),
                (
                    "rom",
                    models.PositiveIntegerField(
                        verbose_name="Вбудована пам'ять (ROM) в ГБ"
                    ),
                ),
                (
                    "battery_capacity",
                    models.PositiveIntegerField(
                        verbose_name="Ємність батареї (мА·год)"
                    ),
                ),
                (
                    "screen_size",
                    models.FloatField(verbose_name="Розмір екрану (дюйми)"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smartphone",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
