# Generated by Django 5.1.4 on 2024-12-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("shop", "0004_rename_image_url_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CableAndAdapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cable_type",
                    models.CharField(max_length=50, verbose_name="Тип кабелю"),
                ),
                (
                    "length_cm",
                    models.PositiveIntegerField(verbose_name="Довжина кабелю (см)"),
                ),
                (
                    "max_speed_gbps",
                    models.FloatField(verbose_name="Максимальна швидкість (Gbps)"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_adapter",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=100, verbose_name="Матеріал")),
                ("compatible_models", models.TextField(verbose_name="Сумісні моделі")),
                ("color", models.CharField(max_length=50, verbose_name="Колір")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Charger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_power_w",
                    models.PositiveIntegerField(verbose_name="Потужність (Вт)"),
                ),
                ("ports", models.PositiveIntegerField(verbose_name="Кількість портів")),
                (
                    "fast_charge",
                    models.BooleanField(default=False, verbose_name="Швидка зарядка"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charger",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity_mAh",
                    models.PositiveIntegerField(
                        verbose_name="Ємність батареї (мА·год)"
                    ),
                ),
                (
                    "output_power_w",
                    models.PositiveIntegerField(verbose_name="Потужність (Вт)"),
                ),
                (
                    "usb_ports",
                    models.PositiveIntegerField(verbose_name="Кількість USB портів"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_bank",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreenProtector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hardness_rating",
                    models.CharField(max_length=20, verbose_name="Рейтинг твердості"),
                ),
                (
                    "anti_glare",
                    models.BooleanField(
                        default=False, verbose_name="Антиблікове покриття"
                    ),
                ),
                ("compatible_models", models.TextField(verbose_name="Сумісні моделі")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_protector",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
