# Generated by Django 5.1.4 on 2024-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_cableandadapter_case_charger_powerbank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cableandadapter",
            name="max_speed_gbps",
        ),
        migrations.AddField(
            model_name="cableandadapter",
            name="connector_1",
            field=models.TextField(null=True, verbose_name="Розʼєм 1"),
        ),
        migrations.AddField(
            model_name="cableandadapter",
            name="connector_2",
            field=models.TextField(null=True, verbose_name="Розʼєм 2"),
        ),
        migrations.AddField(
            model_name="powerbank",
            name="supports_wireless_charging",
            field=models.BooleanField(
                default=False, verbose_name="Підтримка бездротової зарядки"
            ),
        ),
        migrations.AddField(
            model_name="powerbank",
            name="type",
            field=models.TextField(null=True, verbose_name="Тип батареї"),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="additional_features",
            field=models.TextField(
                blank=True,
                help_text="Наприклад: підтримка стилуса, безпровідна зарядка",
                null=True,
                verbose_name="Додаткові функції",
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="brand",
            field=models.TextField(blank=True, null=True, verbose_name="Бренд"),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="camera_specifications",
            field=models.CharField(
                help_text="Наприклад: 108МП + 12МП + 5МП",
                max_length=255,
                null=True,
                verbose_name="Характеристики камер",
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="display_type",
            field=models.CharField(
                help_text="Наприклад: AMOLED, IPS, LCD",
                max_length=100,
                null=True,
                verbose_name="Тип дисплея",
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="hz_of_display",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Частота диcплею"
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="operating_system",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Операційна система"
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="supports_5g",
            field=models.BooleanField(default=False, verbose_name="Підтримка 5G"),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="waterproof_rating",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: IP68",
                max_length=50,
                null=True,
                verbose_name="Клас захисту (водостійкість)",
            ),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Вага (грам)"),
        ),
    ]
