# Generated by Django 5.1.4 on 2024-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_cableandadapter_max_speed_gbps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cableandadapter",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="powerbank",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="screenprotector",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AlterField(
            model_name="smartphone",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Бренд"
            ),
        ),
    ]
