# Generated by Django 5.1.4 on 2024-12-12 07:34

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shop.models.product_image_path,
                verbose_name="Картинка",
            ),
        ),
    ]
