# Generated by Django 5.1.4 on 2024-12-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_url",
            new_name="image",
        ),
    ]
