# Generated by Django 5.1.4 on 2024-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Очікується", "Очікується"),
                    ("Підтверджено", "Підтверджено"),
                    ("Відправлено в службу доставки", "Відправлено в службу доставки"),
                    ("Доставляється", "Доставляється"),
                    ("Завершено", "Завершено"),
                    ("Cancelled", "Скасовано"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
