# Generated by Django 5.1.4 on 2024-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Очікується", "Очікується"),
                    ("Підтверджено", "Підтверджено"),
                    ("Відправлено в службу доставки", "Відправлено в службу доставки"),
                    ("Доставляється", "Доставляється"),
                    ("Завершено", "Завершено"),
                    ("Скасовано", "Скасовано"),
                ],
                default="Очікується",
                max_length=100,
            ),
        ),
    ]
